package com.emfitsolutions.gopreach.data.local.psgc

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Philippine Standard Geographic Code (PSGC) reference data — Province ->
 * City/Municipality -> Barangay, bundled read-only in `assets/databases/psgc.db`
 * (see [PsgcDatabase]'s doc comment) and opened via Room's `createFromAsset`.
 * These three entities' table/column names must match that prebuilt file
 * exactly (built by a one-off script from the PSA's own PSGC publication,
 * not generated by this app) — there is no migration path for this database,
 * only a full asset replacement if the PSGC itself is ever updated.
 *
 * [nameNormalized] (uppercase, punctuation/parenthetical-suffix stripped —
 * e.g. "Adams (Pob.)" -> "ADAMS") exists purely so [PsgcDao]'s search queries
 * and the reverse-geocode auto-fill match (see [com.emfitsolutions.gopreach
 * .data.repository.PhilippineLocationRepository]) can compare against a
 * predictable, case/format-insensitive form without recomputing it on every
 * query; [name] is always what's actually shown to the publisher.
 */
@Entity(tableName = "province")
data class ProvinceEntity(
    @PrimaryKey val id: Int,
    val name: String,
    val nameNormalized: String,
)

@Entity(tableName = "muncity")
data class MuncityEntity(
    @PrimaryKey val id: Int,
    val provinceId: Int,
    val name: String,
    val nameNormalized: String,
)

@Entity(tableName = "barangay")
data class BarangayEntity(
    @PrimaryKey val id: Int,
    val muncityId: Int,
    val name: String,
    val nameNormalized: String,
)
